tech-request/src/main/java/com/cy/tech/request/web/controller/component/assigndep/vo/AssignUnitVO.java
/**
 * 
 */
package com.cy.tech.request.web.controller.component.assigndep.vo;

import java.io.Serializable;
import java.util.List;

import com.cy.tech.request.logic.vo.PtCheckTo;
import com.cy.tech.request.logic.vo.WorkOnpgTo;
import com.cy.tech.request.logic.vo.WorkTestInfoTo;
import com.cy.tech.request.vo.enums.ReqConfirmDepCompleteType;
import com.cy.tech.request.vo.enums.ReqConfirmDepProgStatus;

import lombok.Getter;
import lombok.Setter;

/**
 * @author allen1214_wu
 *
 */
public class AssignUnitVO implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7762249434385532045L;

    /**
     * 單位 SID
     */
    @Setter
    @Getter
    private Integer depSid;

    /**
     * 單位名稱
     */
    @Setter
    @Getter
    private String depName;
    
    /**
     * 單位名稱
     */
    @Setter
    @Getter
    private String depFullName;

    /**
     * 負責人名稱
     */
    @Setter
    @Getter
    private String ownerName;

    /**
     * 處理進度
     */
    @Setter
    @Getter
    private ReqConfirmDepProgStatus progressStatus;
    
    @Setter
    @Getter
    private ReqConfirmDepCompleteType completeType;
    
    /**
     * 原型確認單資訊
     */
    @Setter
    @Getter
    List<PtCheckTo> ptChecks;
    
    /**
     * 送測單資訊
     */
    @Setter
    @Getter
    List<WorkTestInfoTo> workTestInfos;
    
    /**
     * 
     */
    @Setter
    @Getter
    List<WorkOnpgTo> onpgInfos;

    /**
     * 進度條 CSS
     * 
     * @return
     */
    public String getProgressStyle() {
        if (this.progressStatus == null) {
            return "";
        }
        return "width:" + this.progressStatus.getProgressPercent() + "%;"
                + "background-color:" + this.progressStatus.getProgressColer() + ";";
    }
    
    public String getProgressHtml() {
        return "<div class='assignDepWorkPanel-progress'>"
                + "<div class='assignDepWorkPanel-progress-bar' style='" + this.getProgressStyle()+ "' /></div>";
    }
    
    public String getCompleteResultTooltip() {
        if(ReqConfirmDepProgStatus.COMPLETE.equals(this.getProgressStatus())) {
            return "2019/11/10 " + this.ownerName + " : balbalbalbalbal"; 
        }
        return "";
    }

    /**
     * 處理進度名稱
     * 
     * @return
     */
    public String getProgressStatusName() {
        if (this.progressStatus == null) {
            return "";
        }
        
        if(ReqConfirmDepProgStatus.COMPLETE.equals(this.getProgressStatus())) {
            if (this.completeType == null) {
                return this.progressStatus.getLabel();
            }
            return this.completeType.getLabel();
        }
        
        return this.progressStatus.getLabel();
    }
    
    public Integer getProgressPercent() {
        if (this.progressStatus == null) {
            return 0;
        }
        return this.progressStatus.getProgressPercent();
    }

    /**
     * 工作清單
     */
    @Setter
    @Getter
    private String workInfo;
    
    
    /**
     * 負責人名稱
     */
    @Setter
    @Getter
    private Integer sortSeq = 0;

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((depSid == null) ? 0 : depSid.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AssignUnitVO other = (AssignUnitVO) obj;
        if (depSid == null) {
            if (other.depSid != null)
                return false;
        } else if (!depSid.equals(other.depSid))
            return false;
        return true;
    }
}

tech-request/src/main/java/com/cy/tech/request/web/attachment/TrOsAttachServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.tech.request.web.attachment;

import com.cy.tech.request.logic.vo.AttachmentVO;
import com.cy.tech.request.web.attachment.util.AttachmentUtils;
import com.cy.tech.request.web.attachment.util.AttachServlet;
import com.cy.tech.request.web.controller.logic.component.OthSetSettingAttachmentLogicComponents;
import java.io.File;
import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author brain0925_liao
 */
@WebServlet("/TrOsAttachServlet")
public class TrOsAttachServlet extends HttpServlet implements AttachServlet {
    //要覆寫

    /**
     * 
     */
    private static final long serialVersionUID = -5901023517366121420L;
    public final static String SERVLET_NAME = TrOsAttachServlet.class.getSimpleName();

    @Override
    public AttachmentVO getAttachAttachmentVOBySid(Object attachmentSid) {
         return OthSetSettingAttachmentLogicComponents.getInstance().getAttachmentVOByAttachment(String.valueOf(attachmentSid));
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        AttachServlet.super.doGet(request, response, super.getServletContext());
    }

    @Override
    public File getServerSideFile(AttachmentVO attachment) {
        return AttachmentUtils.getServerSideFile(attachment, "tech-request");
    }
}

tech-request/src/main/java/com/cy/tech/request/web/attachment/util/AttachServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.tech.request.web.attachment.util;


import com.cy.tech.request.logic.vo.AttachmentVO;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.MessageFormat;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 附件預覽元件
 * @author brain0925_liao
 */
public interface AttachServlet {
    
    public final static String PARAM_SID_KEY = "sid";
    public final static String PARAM_TIME_KEY = "time";
    public final static String PARAM_ATTACH_SERVICE_KEY = "service";
    
    final Logger logger = LoggerFactory.getLogger(AttachServlet.class);
    
    default void doGet(HttpServletRequest request, HttpServletResponse response, ServletContext servletContext) throws ServletException, IOException {
        Object attachmentSid = this.findAttachSid(request);
        String uploadTime = this.getUploadTimeParameter(request);
        AttachmentVO attachment = this.getAttachAttachmentVOBySid(attachmentSid);
        File attachmentFile = this.getServerSideFile(attachment);
        if (!this.validateParameters(attachment, uploadTime, attachmentFile)) {
            response.setStatus(HttpServletResponse.SC_NOT_FOUND);
            return;
        }
        this.sendAttachment(request, response, servletContext, attachment, attachmentFile);
    }
    
    default void sendAttachment(HttpServletRequest request, HttpServletResponse response, ServletContext servletContext,
            AttachmentVO attachment, File attachmentFile) throws IOException {
        String encodedFileName = AttachmentUtils.encodeFileName(attachment.getAttName());
        String mimeType
                = AttachmentUtils.getNoneNullMimeType(servletContext, attachment.getAttName());
        String contentDispositionPattern
                = AttachmentUtils.isMSIE(request)
                ? "{0}; filename=\"{1}\""
                : "{0}; filename=\"{1}\"; filename*=UTF-8''{1}";
        String contentDisposition
                = MessageFormat.format(contentDispositionPattern, "inline", encodedFileName);
        FileInputStream in = new FileInputStream(attachmentFile);
        OutputStream out = response.getOutputStream();
        
        response.setContentType(mimeType);
        response.setContentLength((int) attachmentFile.length());
        response.setHeader("Content-Disposition", contentDisposition);
        
        try {
            IOUtils.copy(in, out);
            out.flush();
        } finally {
            IOUtils.closeQuietly(in);
        }
    }
    
    default boolean validateParameters(AttachmentVO attachment, String uploadTime, File attachmentFile) {
        // 檢查 attachment.getCreated() 是為了預防使用者從 URL 修改 sid 即可取得其他檔案.
        return checkParam(attachment, uploadTime, attachmentFile)
                && uploadTime.equals(attachment.getParamCreateTime())
                && checkAttachmentFile(attachmentFile);
    }
    
    default boolean checkParam(AttachmentVO attachment, String uploadTime, File attachmentFile) {
        return attachment != null && uploadTime != null && attachmentFile != null;
    }
    
    default boolean checkAttachmentFile(File attachmentFile) {
        return attachmentFile.exists() && attachmentFile.isFile();
    }
    
    public AttachmentVO getAttachAttachmentVOBySid(Object attachmentSid);
    
    public File getServerSideFile(AttachmentVO attachment);
    
    default Object findAttachSid(HttpServletRequest request) {
        return this.getAttachmentSidParameter(request);
    }
    
    default String getAttachmentServiceParameter(HttpServletRequest request) {
        return request.getParameter(PARAM_ATTACH_SERVICE_KEY);
    }
    
    default String getAttachmentSidParameter(HttpServletRequest request) {
        return request.getParameter(PARAM_SID_KEY);
    }
    
    default String getUploadTimeParameter(HttpServletRequest request) {
        try {
            String timeString = request.getParameter(PARAM_TIME_KEY);
            return timeString;
        } catch (Exception e) {
            logger.error("getUploadTimeParameter Error ", e);
            return "";
        }
    }
}

tech-request/src/main/java/com/cy/tech/request/web/controller/component/qkstree/AbstractQucikSelectTreeComponentMBean.java
package com.cy.tech.request.web.controller.component.qkstree;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.primefaces.model.TreeNode;

import com.cy.work.common.utils.WkStringUtils;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.Gson;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

/**
 * @author allen
 *
 */
@Slf4j
public abstract class AbstractQucikSelectTreeComponentMBean implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 253814940429940201L;

    public static final String STYLE_CONTENT_TRUE_DATA = "STYLE_CONTENT_TRUE_DATA";

    /**
     * 
     */
    protected QuickSelectTreeCallback callback;

    @Getter
    private String memoMessage = "※&nbsp;<span style='font-weight: bold;text-decoration:underline;'>雙擊&nbsp;</span>清單項目選取 (雙擊項目後移至右邊或左邊)";

    /**
     * 樹節點結構資料
     */
    @Getter
    protected TreeNode rootTreeNode;

    /**
     * 選擇的節點
     */
    @Getter
    @Setter
    protected TreeNode selectedNode;

    /**
     * 
     */
    @Getter
    protected List<?> selectedList;

    /**
     * 是否顯示停用
     */
    @Getter
    @Setter
    protected Boolean queryShowInactiveNode = false;

    /**
     * 
     */
    protected Map<String, AbstractTreeComponentNodeData> allNodeDataMapByRowKey;
    protected Map<String, AbstractTreeComponentNodeData> allNodeDataMapBySid;

    /**
     * 
     */
    @Getter
    protected String nodeDataJsonString = "";

    /**
     * 
     */
    @Getter
    @Setter
    protected String selectedNodeDataJsonString = "";

    /**
     * 連動資料
     */
    @Getter
    @Setter
    protected String linkageMapJsonString = "";

    /**
     * 
     */
    @Getter
    @Setter
    protected boolean selectedListMode = false;

    /**
     * 訊息
     */
    @Getter
    public String message = "";

    /**
     * 切換顯示模式(正常/停用)
     */
    public abstract void switchShowActiveOrinactiveMode();

    /**
     * @return
     */
    public abstract List<?> getSelectedDataList();

    @Getter
    public boolean renderFlag = false;

    public void preOpenDlg() {
        // log.debug("preOpenDlg");
        this.renderFlag = true;
    }

    public void afterCloseDlg() {
        // log.debug("afterCloseDlg");
        this.renderFlag = false;
    }

    /**
     * 在初始化前執行
     */
    protected void brforeInitialize(
            QuickSelectTreeCallback callback) {

        // 記錄傳入參數
        this.callback = callback;

        // 預設不【顯示停用】
        this.queryShowInactiveNode = false;
        //
        this.nodeDataJsonString = "{}";
        this.selectedNodeDataJsonString = "[]";
        renderFlag = false;
    }

    /**
     * 初始化後執行
     */
    protected void afterInitialize() {
    }

    /**
     * 
     */
    protected void afterbuildTreeData() {
        // ====================================
        // 整理資料
        // ====================================
        // 將TreeNode 轉為 list
        List<TreeNode> allNodelist = Lists.newArrayList();
        this.treeNodeToList(allNodelist, this.rootTreeNode);

        // 轉為 map 形式
        this.allNodeDataMapByRowKey = Maps.newHashMap();
        this.allNodeDataMapBySid = Maps.newHashMap();

        for (TreeNode eachNode : allNodelist) {
            if (eachNode.getData() == null) {
                continue;
            }
            AbstractTreeComponentNodeData nodeData = (AbstractTreeComponentNodeData) eachNode.getData();
            nodeData.setRowKey(eachNode.getRowKey());

            if (this.allNodeDataMapByRowKey.containsKey(eachNode.getRowKey())) {
                log.info("節點重複[" + eachNode.getRowKey() + ""
                        + "原節點[" + this.allNodeDataMapByRowKey.get(eachNode.getRowKey()).getOuName() + "]"
                        + "新節點[" + nodeData.getOuName() + "]");
            }

            this.allNodeDataMapByRowKey.put(eachNode.getRowKey(), nodeData);

            this.allNodeDataMapBySid.put(this.getAllNodeDataSidMapKey(nodeData), nodeData);

        }
        // 轉JSON以供 client 端調用
        this.nodeDataJsonString = new Gson().toJson(this.allNodeDataMapByRowKey);

        // 連動項目資料（子項實做）
        this.prepareLinkageData();
    }

    /**
     * @param nodeData
     * @return
     */
    public String getAllNodeDataSidMapKey(AbstractTreeComponentNodeData nodeData) {
        return this.getAllNodeDataSidMapKey(nodeData.isDataNode(), nodeData.getSid());
    }

    public String getAllNodeDataSidMapKey(boolean isDataNode, String nodeSid) {
        return isDataNode + nodeSid;
    }

    /**
     * @param nodeData
     * @return
     */
    public String getNodeDisplayContext(AbstractTreeComponentNodeData nodeData) {
        if (nodeData == null) {
            return "";
        }

        // 取得顯示名稱字串
        String displayContext = this.getNodeName(nodeData);
        // 為user 節點時, 前方加入 icon
        if (nodeData.isDataNode()) {
            displayContext = ""
                    + "<span class=\"quick-select-tree-data-node-highlight\">"
                    + "<i class=\"fa\">"
                    + "</i>&nbsp;&nbsp;"
                    + displayContext
                    + "</span>";
        }

        return displayContext;
    }

    /**
     * 取得節點名稱
     * 
     * @param nodeData
     * @return
     */
    public String getNodeName(AbstractTreeComponentNodeData nodeData) {

        String displayName = "<span class='ui-treenode-name'></span>";

        // 取得 node data
        if (nodeData == null) {
            return displayName;
        }

        // 取得節點名稱
        displayName = WkStringUtils.removeCtrlChr(WkStringUtils.safeTrim(nodeData.getName()));

        // 加上 class 標示 (client script 用)
        return "<span class='ui-treenode-name'>" + displayName + "</span>";
    }

    /**
     * 將所有樹狀節點加入list中
     *
     * @param list
     * @param root
     */
    protected void treeNodeToList(List<TreeNode> list, TreeNode root) {
        if (root == null || root.getChildren() == null) {
            return;
        }
        root.getChildren().forEach(each -> {
            list.add(each);
            this.treeNodeToList(list, each);
        });
    }

    /**
     * 準備連動資料 (需 overwrite)
     */
    public void prepareLinkageData() {
        this.linkageMapJsonString = "{}";
    }

    /**
     * @author allen1214_wu
     *
     */
    @Data
    public abstract class AbstractTreeComponentNodeData implements Serializable {

        /**
         * 
         */
        private static final long serialVersionUID = 7711451727966382020L;

        /**
         * 標註僅進行一次連動
         */
        public static final String INFO_KEY_NOT_COMBO_LINKAGE = "NOT_COMBO_LINKAGE";

        /**
         * 名稱
         */
        protected String name;
        /**
         * SID
         */
        protected String sid;
        /**
         * 是否為 『可選擇』 節點 (非階層)
         */
        protected boolean dataNode = false;
        /**
         * tree node key
         */
        protected String rowKey;
        /**
         * 是否啟用
         */
        protected boolean active = false;
        /**
         * 顯示用名稱
         */
        protected String ouName;

        /**
         * 其他註記資料
         */
        protected Map<String, String> otherInfo = Maps.newHashMap();
    }
}

tech-request/src/main/webapp/resources/components/assign_send_info.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:cc="http://java.sun.com/jsf/composite"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<!-- 需求單分派通知資訊-->
	<cc:interface>
		<cc:attribute
			name="model"
			required="true"
			shortDescription="bean"
			type="com.cy.tech.request.web.controller.require.AssignSendInfoComponent" />
	</cc:interface>

	<cc:implementation>
		<p:outputPanel
			style="padding: 5px 5px 0px 0px;"
			rendered="#{not empty cc.attrs.model}">
			<!-- 若還未初始化, 執行到此行時強制觸發取得資料 -->
			<p:outputLabel value="#{cc.attrs.model.passiveInitForView()}" />
			<p:panelGrid>
				<!-- 顯示樣式一, 暫不顯示 -->
				<p:row rendered="false">
					<p:column style="vertical-align: top; ">
						<p:outputLabel
							value="分派結果："
							style="font-weight:bolder;color:blue;padding: 5px 0px 5px 5px;" />
						<p:scrollPanel
							style="border:none;max-height:300px;max-width:500px;margin: 5px 0px 5px 10px;"
							mode="native">
							<p:outputLabel
								value="#{cc.attrs.model.resultAssignDepsInfo}"
								escape="false" />
						</p:scrollPanel>
					</p:column>
					<p:column
						rendered="#{not empty cc.attrs.model.resultSendDepsInfo}"
						style="vertical-align: top;">
						<p:outputLabel
							value="通知單位："
							style="font-weight:bolder;color:blue;padding: 5px 0px 5px 5px;" />
						<p:scrollPanel
							style="border:none;max-height:300px;max-width:500px;margin: 5px 0px 5px 10px;"
							mode="native">
							<p:outputLabel
								value="#{cc.attrs.model.resultSendDepsInfo}"
								escape="false" />
						</p:scrollPanel>
					</p:column>
				</p:row>
				<!-- 顯示樣式二 -->
				<p:row>
					<p:column
						rendered="#{not empty cc.attrs.model.resultAssignDepTree}"
						style="vertical-align: top;">
						<p:outputLabel
							value="分派結果："
							style="font-weight:bolder;color:blue;padding: 5px 0px 5px 5px;" />
						<p:scrollPanel
							style="border:none;max-height:300px;margin: 5px 0px 5px 10px;"
							mode="native">
							<p:tree
								value="#{cc.attrs.model.resultAssignDepTree}"
								var="item"
								style="border:none;"
								selectionMode="single">
								<p:treeNode>
									<p:outputLabel
										value="#{item.showName}"
										escape="false" />
								</p:treeNode>
							</p:tree>
						</p:scrollPanel>
					</p:column>
					<p:column
						rendered="#{not empty cc.attrs.model.resultSendDepTree}"
						style="vertical-align: top;">
						<p:outputLabel
							value="通知結果："
							style="font-weight:bolder;color:blue;padding: 5px 0px 5px 5px;" />
						<p:scrollPanel
							style="border:none;max-height:300px;margin: 5px 0px 5px 10px;"
							mode="native">
							<p:tree
								value="#{cc.attrs.model.resultSendDepTree}"
								var="item"
								style="border:none;"
								selectionMode="single">
								<p:treeNode>
									<p:outputLabel
										value="#{item.showName}"
										escape="false" />
								</p:treeNode>
							</p:tree>
						</p:scrollPanel>
					</p:column>
				</p:row>
			</p:panelGrid>
		</p:outputPanel>

		<p:outputPanel
			style="padding: 5px 5px 0px 0px;"
			rendered="#{not empty cc.attrs.model}">

			<p:outputLabel
				value="分派/通知歷程："
				style="font-weight:bolder;color:blue;padding: 5px 0px 5px 5px;" />

			<p:scrollPanel
				style="border:none;max-height:300px;margin: 5px 0px 5px 15px;"
				mode="native">
				<p:dataTable
					value="#{cc.attrs.model.historys}"
					var="history"
					rowKey="#{history.sid}"
					rowIndexVar="index"
					resizableColumns="true"
					resizeMode="expand"
					emptyMessage="尚無分派/通知單位歷程"
					selectionMode="single">
					<p:column
						headerText="執行時間"
						style="width:120px">
						<p:outputLabel value="#{history.createdDate}">
							<f:convertDateTime pattern="yyyy/MM/dd HH:mm:ss" />
						</p:outputLabel>
					</p:column>
					<p:column
						headerText="執行者"
						style="width:400px">
						<p:outputLabel
							value="#{history.show_creater}"
							escape="false" />
					</p:column>
					<p:column headerText="加派部門">
						<p:outputLabel
							value="#{history.show_addAssignDeps}"
							escape="false" />
						<p:tooltip
							for="@previous"
							value="#{history.showTreeStyle_addAssignDeps}"
							escape="false"
							trackMouse="true" />
					</p:column>
					<p:column headerText="減派部門">
						<p:outputLabel
							value="#{history.show_deleteAssignDeps}"
							escape="false" />
						<p:tooltip
							for="@previous"
							value="#{history.showTreeStyle_deleteAssignDeps}"
							escape="false"
							trackMouse="true" />
					</p:column>
					<p:column headerText="通知部門">
						<p:outputLabel
							value="#{history.show_addSendDeps}"
							escape="false" />
						<p:tooltip
							for="@previous"
							value="#{history.showTreeStyle_addSendDeps}"
							escape="false"
							trackMouse="true" />
					</p:column>
					<p:column headerText="移除通知部門">
						<p:outputLabel
							value="#{history.show_deleteSendDeps}"
							escape="false" />
						<p:tooltip
							for="@previous"
							value="#{history.showTreeStyle_deleteSendDeps}"
							escape="false"
							trackMouse="true" />
					</p:column>
				</p:dataTable>
			</p:scrollPanel>
		</p:outputPanel>
		<br />
		<br />
		<br />
		<br />
	</cc:implementation>
</ui:composition>

tech-request/src/main/webapp/resources/components/reqConfirmDepPanel_overview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:cp="http://java.sun.com/jsf/composite/components"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:pe="http://primefaces.org/ui/extensions">

<p:outputPanel styleClass="reqConfirmDepPanel_datatable">
    <br />
    <br />
    <br />
    <p:dataTable
        style="width:700px;padding-left:3px"
        scrollHeight="400"
        var="unitVO"
        value="#{cc.attrs.model.allRequireConfirmDepVOs}"
        rowKey="#{unitVO.depSid}"
        rowIndexVar="unitIndex"
        scrollable="true"
        selection="false"
        draggableRows="false"
        emptyMessage="尚未進行分派,或無非停用的分派單位">
        <p:column
            headerText="序"
            width="30"
            styleClass="alignCenter"
            sortBy="#{unitVO.seqNum}">
            <h:outputText value="#{unitVO.seqNum + 1}" />
        </p:column>
        <p:column
            width="100"
            headerText="單位名稱"
            sortBy="#{unitVO.depName}">
            <p:outputPanel
                style="width:100%;white-space:nowrap;"
                styleClass="cy-hover-highlight">
                <h:outputText
                    escape="false"
                    value="#{unitVO.depName}" />
            </p:outputPanel>
            <p:tooltip
                for="@previous"
                value="#{unitVO.depFullName}"
                escape="false"
                trackMouse="true" />
        </p:column>
        <p:column
            width="100"
            headerText="負責人"
            sortBy="#{unitVO.ownerName}">
            <h:outputText
                escape="false"
                value="#{unitVO.ownerName}" />
        </p:column>
        <p:column
            width="40"
            headerText="追蹤"
            styleClass="alignCenter">
            <p:outputPanel
                rendered="#{not empty unitVO.isNoTrace()}"
                style="width:100%;white-space:nowrap;"
                styleClass="cy-hover-highlight">
                <h:outputText value="追蹤" />
            </p:outputPanel>
            <pe:tooltip
                rendered="#{not empty unitVO.isNoTrace()}"
                for="@previous"
                adjustX="-10"
                adjustY="-10"
                fixed="true">
                <p:outputPanel style="width:700px">
                    <ui:include src="reqConfirmDepPanel_dep_trace.xhtml">
                        <ui:param
                            name="depTraceModel"
                            value="#{unitVO}" />
                        <ui:param
                            name="depTraceScrollable"
                            value="true" />
                    </ui:include>
                </p:outputPanel>
            </pe:tooltip>
        </p:column>
        <p:column
            headerText="處理進度"
            sortBy="#{unitVO.progressPercent}">
            <p:panelGrid>
                <p:row>
                    <p:column>
                        <p:outputLabel
                            value="#{unitVO.getProgressHtml()}"
                            escape="false" />
                    </p:column>
                    <p:column style="width:100px">
                        <p:outputLabel
                            style="font-weight: bold;"
                            value="#{unitVO.getProgStatusName()}" />
                    </p:column>
                </p:row>
            </p:panelGrid>
        </p:column>
        <p:column
            width="60"
            headerText="完成說明"
            styleClass="alignCenter">
            <p:outputPanel
                rendered="#{not empty unitVO.completeMemo}"
                style="width:100%;white-space:nowrap;"
                styleClass="cy-hover-highlight">
                <h:outputText value="說明" />
            </p:outputPanel>
            <p:tooltip
                for="@previous"
                rendered="#{not empty unitVO.completeMemo}"
                value="#{unitVO.completeMemo}"
                trackMouse="true" />
        </p:column>
    </p:dataTable>
    <!-- 需要覆寫 max-width 不然會只有 280px 導致跑版 -->
    <style type="text/css">
        .ui-tooltip, .qtip{
            max-width: 720px !important;
        }
    </style>
</p:outputPanel>
</html>